---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
# ... CONFIG ...
    exclude_fingerprints:
      - 96bc6b4c93d63046854622bc3d48ac53
      - 46e2087edf86c6edc1f061ee70ca84e5
      - b2037d198136dfa1e6b0f5187a7cf74e
      - b3af9fe452995ee88d2478216b5c8fcd
      - 2fff042a0a30cee23a2d6795d79a1144
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
    exclude_fingerprints:
      - 0c21d81e710f4914b2519d4dde776459
      - 993dd9590fef4f2624e01b5836fb13e6
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
