---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
# ... CONFIG ...
    exclude_fingerprints:
      - 96bc6b4c93d63046854622bc3d48ac53
      - 46e2087edf86c6edc1f061ee70ca84e5
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
